//! Racelogic VBO text export in the RaceBox layout OVRLEY ships a fixture for.
//!
//! ```text
//! File created on 16/09/2026 @ 09:59
//!
//! [header]
//! time
//! lat
//! long
//! velocity kmh
//! heading
//! height
//! LongAcc
//! LatAcc
//! VertAcc
//! sats
//!
//! [comments]
//! ...
//!
//! [column names]
//! time lat long velocity heading height LongAcc LatAcc VertAcc sats
//!
//! [data]
//! 095953.000 +03345.00000 -02257.20000 012.345 123.45 +00150.00 +0.050 +0.061 +0.991 12
//! ```
//!
//! Latitude/longitude are in minutes, longitude **positive west** (Racelogic
//! convention, which OVRLEY negates on import). Time is `HHMMSS.sss` of the
//! camera clock. Without a GPS fix the position channels are omitted.

use std::fmt::Write as _;

use super::{APP_NAME, APP_VERSION};
use crate::process::Telemetry;

fn signed_axis(axis: crate::process::Axis, invert: bool) -> String {
    format!("{}{}", if invert { "-" } else { "" }, axis.label())
}

pub fn render(telemetry: &Telemetry, source_name: &str) -> String {
    let with_gps = telemetry.has_gps();
    let info = &telemetry.info;
    let mut out = String::with_capacity(telemetry.rows.len() * 80 + 512);

    let created = info
        .start_local
        .map(|dt| dt.format("%d/%m/%Y @ %H:%M").to_string())
        .unwrap_or_else(|| "01/01/2000 @ 00:00".to_string());
    let _ = writeln!(out, "File created on {created}");
    out.push('\n');

    let mut header: Vec<&str> = vec!["time"];
    if with_gps {
        header.extend(["lat", "long", "velocity kmh", "heading", "height"]);
    }
    header.extend(["LongAcc", "LatAcc", "VertAcc"]);
    if with_gps {
        header.push("sats");
    }
    let mut columns: Vec<&str> = vec!["time"];
    if with_gps {
        columns.extend(["lat", "long", "velocity", "heading", "height"]);
    }
    columns.extend(["LongAcc", "LatAcc", "VertAcc"]);
    if with_gps {
        columns.push("sats");
    }

    out.push_str("[header]\n");
    for h in &header {
        let _ = writeln!(out, "{h}");
    }
    out.push('\n');

    out.push_str("[comments]\n");
    let _ = writeln!(out, "Generated by {APP_NAME} {APP_VERSION}");
    let _ = writeln!(out, "Source : {source_name}");
    if let Some(m) = &info.model {
        let _ = writeln!(out, "Camera : {m}");
    }
    if let Some(s) = &info.serial {
        let _ = writeln!(out, "Serial Number : {s}");
    }
    if let Some(r) = &info.remote_name {
        let _ = writeln!(out, "GPS Remote : {r}");
    }
    if let Some(utc) = info.start_utc() {
        let _ = writeln!(out, "UTC Date Started : {}", utc.format("%d/%m/%Y %H:%M:%S"));
    }
    let _ = writeln!(
        out,
        "Acceleration : gravity {} ({}), lateral {} longitudinal {} vertical {}",
        match telemetry.gravity_used {
            crate::process::GravityMode::None => "kept",
            _ => "removed",
        },
        telemetry.gravity_used.cli_name(),
        signed_axis(
            telemetry.options.axes.lateral,
            telemetry.options.axes.invert_lateral
        ),
        signed_axis(
            telemetry.options.axes.longitudinal,
            telemetry.options.axes.invert_longitudinal
        ),
        signed_axis(
            telemetry.options.axes.vertical,
            telemetry.options.axes.invert_vertical
        ),
    );
    if !with_gps {
        out.push_str("GPS : no fix in this clip, position channels omitted\n");
    }
    out.push('\n');

    out.push_str("[column names]\n");
    let _ = writeln!(out, "{}", columns.join(" "));
    out.push('\n');

    out.push_str("[data]\n");
    for r in &telemetry.rows {
        let mut cols: Vec<String> = Vec::with_capacity(columns.len());
        let tod = match telemetry.local_time(r.t) {
            Some(dt) => {
                use chrono::Timelike;
                let secs = f64::from(dt.second()) + f64::from(dt.nanosecond()) / 1e9;
                format!("{:02}{:02}{:06.3}", dt.hour(), dt.minute(), secs)
            }
            None => {
                let h = (r.t / 3600.0).floor();
                let m = ((r.t - h * 3600.0) / 60.0).floor();
                let s = r.t - h * 3600.0 - m * 60.0;
                format!("{:02}{:02}{:06.3}", h as u32, m as u32, s)
            }
        };
        cols.push(tod);
        if with_gps {
            let lat_min = r.latitude.map(|v| v * 60.0).unwrap_or(0.0);
            let lon_min = r.longitude.map(|v| -v * 60.0).unwrap_or(0.0);
            cols.push(format!("{lat_min:+012.5}"));
            cols.push(format!("{lon_min:+013.5}"));
            cols.push(format!("{:07.3}", r.speed_ms.unwrap_or(0.0) * 3.6));
            cols.push(format!("{:06.2}", r.heading_deg.unwrap_or(0.0)));
            cols.push(format!("{:+09.2}", r.altitude_m.unwrap_or(0.0)));
        }
        cols.push(format!("{:+.3}", r.longitudinal.unwrap_or(0.0)));
        cols.push(format!("{:+.3}", r.lateral.unwrap_or(0.0)));
        cols.push(format!("{:+.3}", r.vertical.unwrap_or(0.0)));
        if with_gps {
            cols.push(if r.has_gps() { "12" } else { "0" }.to_string());
        }
        out.push_str(&cols.join(" "));
        out.push('\n');
    }
    out
}

#[cfg(test)]
mod tests {
    use super::super::testutil::telemetry;
    use super::*;

    #[test]
    fn sections_and_columns_with_gps() {
        let t = telemetry(true);
        let text = render(&t, "clip.MP4");
        assert!(text
            .starts_with("File created on 16/09/2026 @ 09:59\n\n[header]\ntime\nlat\nlong\nvelocity kmh\n"));
        assert!(text
            .contains("[column names]\ntime lat long velocity heading height LongAcc LatAcc VertAcc sats\n"));
        let data = text.split("[data]\n").nth(1).unwrap();
        let first = data.lines().next().unwrap();
        let cols: Vec<&str> = first.split(' ').collect();
        assert_eq!(cols.len(), 10);
        assert_eq!(cols[0], "095953.000");
        // 55.75° N -> +03345.00000 minutes, 37.62° E -> west-positive -02257.20000
        assert_eq!(cols[1], "+03345.00000");
        assert_eq!(cols[2], "-002257.20000");
        assert_eq!(cols[9], "12");
    }

    #[test]
    fn no_gps_drops_position_channels() {
        let t = telemetry(false);
        let text = render(&t, "clip.MP4");
        assert!(text.contains("[column names]\ntime LongAcc LatAcc VertAcc\n"));
        let data = text.split("[data]\n").nth(1).unwrap();
        let times: Vec<&str> = data.lines().map(|l| l.split(' ').next().unwrap()).collect();
        // strictly increasing time-of-day tokens (OVRLEY rejects duplicates)
        for w in times.windows(2) {
            assert!(w[1] > w[0], "{} then {}", w[0], w[1]);
        }
        assert!(data.lines().nth(70).unwrap().contains(" +0.800 "));
    }
}
